services:
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"

  rabbitmq:
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_MGMT_PORT:-15672}:15672"

  redis:
    ports:
      - "${REDIS_PORT:-6379}:6379"
